### PR TITLE
arjunmahishi

### PR DESCRIPTION
**Pull request by arjunmahishi**

### CODE REVIEW

**Comment by mgartner** [comment]
I get an error trying to run your submission:

```
➜ ./arjunmahishi
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.main()
        /Users/marcus/workspace/1brcgo/arjunmahishi.go:47 +0x1a4
```

**Comment by mgartner** [comment]
Oh, the `measurements.txt` file is required as an input. I'll run the tests now!

**Comment by arjunmahishi** [comment]
Should have improved a little

image

**Comment by arjunmahishi** [comment]
@mgartner Please re-run this one more time before it ends. Thanks! :)

**Comment by arjunmahishi** [comment]
Decrypted solution in #41

**Pull request closed without merging**
